include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Code style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    
    # Code quality
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_empty_else: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
    # Performance
    avoid_function_literals_in_foreach_calls: true
    prefer_collection_literals: true
    
    # Safety
    always_declare_return_types: true
    require_trailing_commas: true
